import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Dashboard from './dashboard'
import React from 'react'
import { useRouter } from 'next/router'
import { useSession } from "next-auth/react"
import ProtectedRoute from '@/Routes/protectedRoutes'
import Login from './login'
import Shipments from './shipments'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const { data: session, status } = useSession()



	return (
		<>
			<Head>
				<title>Qbuypanda</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{ session ? <Shipments /> : <Login /> }
			</main>
		</>
	)
}
